---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/candidaturas":
    post:
      summary: Adiciona uma candidatura
      tags:
      - Pessoa
      parameters: []
      responses:
        '201':
          description: Vaga criada
        '422':
          description: Requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_pessoa:
                  type: integer
                id_vaga:
                  type: integer
              required:
              - id_pessoa,
              - id_vaga
  "/v1/pessoas":
    post:
      summary: Adiciona uma pessoa
      tags:
      - Pessoa
      parameters: []
      responses:
        '201':
          description: Pessoa adicionada
        '422':
          description: Requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                profissao:
                  type: string
                localizacao:
                  type: string
                nivel:
                  type: integer
                score:
                  type: integer
              required:
              - nome
              - profissao
              - localizacao
              - nivel
              - score
  "/v1/vagas":
    post:
      summary: Adiciona uma vaga
      tags:
      - Vagas
      parameters: []
      responses:
        '201':
          description: Vaga adicionada
        '422':
          description: Requisição inválida
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                empresa:
                  type: string
                titulo:
                  type: string
                descricao:
                  type: string
                localizacao:
                  type: string
                nivel:
                  type: integer
              required:
              - empresa
              - titulo
              - descricao
              - localizacao
              - nivel
    get:
      summary: Lista vagas
      tags:
      - Vagas
      description: Lista todas as vagas disponíveis
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
